[pytest]
DJANGO_SETTINGS_MODULE = controle_epi.settings
python_files = controle_epi/tests.py controle_epi/test_*.py controle_epi/*_tests.py
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
