# Generated by Django 5.2.8 on 2026-02-28 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeAparelho', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=30)),
                ('quantidade', models.IntegerField()),
                ('fotoEPI', models.ImageField(blank=True, null=True, upload_to='static/fotos_epi/')),
                ('validade', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('setor', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=11)),
                ('fotoColaborador', models.ImageField(blank=True, null=True, upload_to='static/fotos_colaboradores/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('setor', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=11)),
                ('fotoGerente', models.ImageField(blank=True, null=True, upload_to='static/fotos_gerentes/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField()),
                ('data_prevista', models.DateField(blank=True, null=True)),
                ('data_devolucao', models.DateField(blank=True, null=True, verbose_name='Registrar Devolução')),
                ('condicao_retirada', models.CharField(choices=[('BOA', 'Boa'), ('USAVEL', 'Usável'), ('RUIM', 'Ruim')], default='BOA', max_length=10)),
                ('condicao_devolucao', models.CharField(blank=True, choices=[('BOA', 'Boa'), ('USAVEL', 'Usável'), ('RUIM', 'Ruim')], max_length=10, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epi_admin.colaborador')),
                ('epi_nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epi_admin.epi')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('data_prevista__gt', models.F('data_emprestimo'))), name='data_prevista_maior_que_emprestimo')],
            },
        ),
    ]
