# Generated by Django 5.2.8 on 2025-11-08 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('setor', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=11)),
                ('fotoColaborador', models.ImageField(blank=True, null=True, upload_to='static/fotos_colaboradores/')),
            ],
        ),
        migrations.CreateModel(
            name='EPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeAparelho', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=30)),
                ('quantidade', models.IntegerField()),
                ('fotoEPI', models.ImageField(blank=True, null=True, upload_to='static/fotos_epi/')),
                ('validade', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('setor', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=11)),
                ('fotoGerente', models.ImageField(blank=True, null=True, upload_to='static/fotos_gerentes/')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField()),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('condicao_retirada', models.CharField(max_length=100)),
                ('condicao_devolucao', models.CharField(blank=True, max_length=100, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epi_admin.colaborador')),
                ('epi_nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epi_admin.epi')),
            ],
        ),
    ]
