# Generated by Django 5.2.8 on 2026-02-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
