# Generated by Django 5.2.8 on 2025-11-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epi_admin', '0002_gerente_user'),
        ('epi_admin', '0002_seed_data'),
    ]

    operations = [
    ]
