# Generated by Django 5.2.8 on 2026-03-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi_admin', '0004_make_email_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='is_ativo',
            field=models.BooleanField(default=True),
        ),
    ]
