# Generated by Django 5.2.8 on 2025-11-29 14:48

import epi_admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi_admin', '0004_colaborador_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='data_prevista',
            field=models.DateField(blank=True, null=True),
        ),
    ]
