# Generated by Django 5.2.8 on 2025-11-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi_admin', '0005_emprestimo_data_prevista'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='emprestimo',
            constraint=models.CheckConstraint(condition=models.Q(('data_prevista__gt', models.F('data_emprestimo'))), name='data_prevista_maior_que_emprestimo'),
        ),
    ]
