# Generated by Django 5.2.8 on 2026-10-09 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi_admin', '0005_colaborador_is_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='epi_admin.colaborador'),
        ),
    ]
