# Generated by Django 5.2.8 on 2025-11-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi_admin', '0006_emprestimo_data_prevista_maior_que_emprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='condicao_devolucao',
            field=models.CharField(blank=True, choices=[('BOA', 'Boa'), ('USAVEL', 'Usável'), ('RUIM', 'Ruim')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='condicao_retirada',
            field=models.CharField(choices=[('BOA', 'Boa'), ('USAVEL', 'Usável'), ('RUIM', 'Ruim')], default='BOA', max_length=10),
        ),
    ]
