# Generated by Django 5.2.8 on 2025-11-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi_admin', '0007_alter_emprestimo_condicao_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True, verbose_name='Registrar Devolução'),
        ),
    ]
